config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :locations
  resources :trips
  devise_for :users
  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  has_rich_text :content
  belongs_to :commenteable, :polymorphic => true
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :trip
  has_many :comments, :as => :commenteable

  validates :name, presence: true
  # TODO:create an after save to convert city country and address in coordinates
  # with google api https://developers.google.com/maps/documentation/geocoding/start

  def self.location_coordinates(user_id)
    locations = Location.joins(:trip).where(trip: { user_id: user_id })
    # TODO:get coordinates of each location and add it to hash or array
  end
end

app/models/travel.rb
class Travel < ApplicationRecord
  has_many :locations
  has_many :comments, :as => :commenteable
  belongs_to :user

  validates :user, :title, presence: true
  validate :date_validation

  def date_validation
    return if start_date.blank?
    if start_date > end_date
      errors.add(:start_date, 'must be smaller than End Date')
    end
  end
end

app/models/trip.rb
class Trip < ApplicationRecord
  has_many :locations
  has_many :comments, :as => :commenteable
  belongs_to :user

  validates :user, :title, presence: true
  validate :date_validation

  def date_validation
    return if start_date.blank?
    if start_date > end_date
      errors.add(:start_date, 'must be smaller than End Date')
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :trips
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.commenteable, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { redirect_to @comment.commenteable, alert: @comment.errors.full_messages }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    commenteable = @comment.commenteable
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to commenteable, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:content, :commenteable_id, :commenteable_type)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_location, only: %i[ show edit update destroy ]

  # GET /locations or /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1 or /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
    @trip = @location.trip
  end

  # POST /locations or /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location.trip, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { redirect_to @location.trip, alert: @location.errors.full_messages.join{','} }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1 or /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: "Location was successfully updated." }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1 or /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: "Location was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def location_params
      params.require(:location).permit(:name, :citye, :country, :address, :trip_id)
    end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_trip, only: %i[ show edit update destroy ]

  # GET /trips or /trips.json
  def index
    @location_coordinates = Location.location_coordinates(current_user.id)
    @trips = Trip.where(user_id: current_user)
    @key = Rails.application.credentials.dig(:google_api, :key)
  end

  # GET /trip/1 or /trip/1.json
  def show
  end

  # GET /trip/new
  def new
    @trip = Trip.new
  end

  # GET /trip/1/edit
  def edit
  end

  # POST /trips or /trips.json
  def create
    @trip = Trip.new(trip_params)
    @trip.user = current_user

    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, notice: "Trip was successfully created." }
        format.json { render :show, status: :created, location: @trip }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trips/1 or /trips/1.json
  def update
    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to @trip, notice: "Trip was successfully updated." }
        format.json { render :show, status: :ok, location: @trip }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1 or /trips/1.json
  def destroy
    @trip.destroy
    respond_to do |format|
      format.html { redirect_to trips_url, notice: "Trip was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      @trip = Trip.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def trip_params
      params.require(:trip).permit(:title, :start_date, :end_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.rich_text_area :content %>
  </div>

  <%= form.hidden_field :commenteable_id, value: commenteable_id %>
  <%= form.hidden_field :commenteable_type, value: commenteable_type %>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<%= @comment.content %>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/home/index.html.erb
<h1>Home</h1>
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

<%= link_to 'My Trips', trips_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mtd</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://maps.googleapis.com/maps/api/js?key='+Rails.application.credentials.dig(:google_api, :key) %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield(:head_tags) %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/locations/_form.html.erb
<%= form_with(model: location) do |form| %>
  <% if location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
        <% location.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <%= form.hidden_field :trip_id, value: @trip.id %>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<h1>Locations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Trip</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.name %></td>
        <td><%= location.address %></td>
        <td><%= location.trip_id %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @location.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @location.address %>
</p>

<p>
  <strong>Trip:</strong>
  <%= @location.trip_id %>
</p>

<% @location.comments.each do |comment| %>
  <p>
    <%= comment.content %>
    <%= link_to 'Delete Comment', comment_path(comment), method: :delete %>
  </p>
<% end %>

<div><a id='add_new_comment' class='clickable_text'>Add new Comment</a></div>
<div class='comment_form'><%= render "comments/form", { commenteable_id: @location.id, commenteable_type: @location.class, comment: Comment.new } %></div>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', trip_path(@location.trip) %>

<script>
  $('.location_form, .comment_form').hide();

  $('#add_new_comment').click(function() {
    $('.comment_form').toggle();
  });
</script>

app/views/map/_index.html.erb
<% provide :head_tags do %>
    <script>
    document.addEventListener("DOMContentLoaded", function(){
      initMap(-34.397, 150.644, [])
    })

    </script>
<% end %>

<div id="map"></div>

app/views/travels/_form.html.erb
<%= form_with(model: travel) do |form| %>
  <% if travel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(travel.errors.count, "error") %> prohibited this travel from being saved:</h2>

      <ul>
        <% travel.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_select :start_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.date_select :end_date %>
  </div>

  <div class="actions">
    <%= form.submit value='Create Journey' %>
  </div>
<% end %>

app/views/travels/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @travel.title %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @travel.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @travel.end_date %>
</p>

<% @travel.comments.each do |comment| %>
  <p>
    <%= comment.content %>
    <%= link_to 'Delete Comment', comment_path(comment), method: :delete %>
  </p>
<% end %>

<p>
  <strong>Locations:</strong>
  <ul>
    <% @travel.locations.each do |location| %>
      <li><%= link_to location.name, location_path(location) %></li>
    <% end %>
  </ul>
</p>

<div><a id='add_new_location' class='clickable_text'>Add new Location</a></div>
<div class='location_form'><%= render 'locations/form', { location: Location.new } %></div>
<div><a id='add_new_comment' class='clickable_text'>Add new Comment</a></div>
<div class='comment_form'><%= render "comments/form", { commenteable_id: @travel.id, commenteable_type: @travel.class, comment: Comment.new } %></div>

<%= link_to 'Edit', edit_travel_path(@travel) %> |
<%= link_to 'Back', travels_path %>

<script>
  $('.location_form, .comment_form').hide();

  $('#add_new_location').click(function() {
    $('.location_form').toggle();
  });

  $('#add_new_comment').click(function() {
    $('.comment_form').toggle();
  });
</script>

app/views/trips/_form.html.erb
<%= form_with(model: trip) do |form| %>
  <% if trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
        <% trip.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_select :start_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.date_select :end_date %>
  </div>

  <div class="actions">
    <%= form.submit value='Create Trip' %>
  </div>
<% end %>

app/views/trips/edit.html.erb
<h1>Editing Trip</h1>

<%= render 'form', trip: @trip %>

<%= link_to 'Show', @trip %> |
<%= link_to 'Back', trips_path %>

app/views/trips/index.html.erb
<h1>My Trips</h1>
<%= link_to 'New Trip', new_trip_path %>
<br>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Start date</th>
      <th>End date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trips.each do |trip| %>
      <tr>
        <td><%= trip.title %></td>
        <td><%= trip.start_date %></td>
        <td><%= trip.end_date %></td>
        <td><%= link_to 'Show', trip, data: { turbolinks: false} %></td>
        <td><%= link_to 'Edit', edit_trip_path(trip) %></td>
        <td><%= link_to 'Destroy', trip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= render "map/index", var: @var%>

app/views/trips/new.html.erb
<h1>New Trip</h1>

<%= render 'form', trip: @trip %>

<%= link_to 'Back', trips_path %>

app/views/trips/show.html.erb
<% provide :head_tags do %>
    <script>
    document.addEventListener("DOMContentLoaded", function(){
      initMap(-34.397, 150.644, [])
    })

    </script>
<% end %>
<p>
  <strong>Title:</strong>
  <%= @trip.title %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @trip.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @trip.end_date %>
</p>

<% @trip.comments.each do |comment| %>
  <p>
    <%= comment.content %>
    <%= link_to 'Delete Comment', comment_path(comment), method: :delete %>
  </p>
<% end %>

<p>
  <strong>Locations:</strong>
  <ul>
    <% @trip.locations.each do |location| %>
      <li><%= link_to location.name, location_path(location) %></li>
    <% end %>
  </ul>
</p>

<div><a id='add_new_location' class='clickable_text'>Add new Location</a></div>
<div class='location_form'><%= render 'locations/form', { location: Location.new } %></div>
<div><a id='add_new_comment' class='clickable_text'>Add new Comment</a></div>
<div class='comment_form'><%= render "comments/form", { commenteable_id: @trip.id, commenteable_type: @trip.class, comment: Comment.new } %></div>

<%= link_to 'Edit', edit_trip_path(@trip) %> |
<%= link_to 'Back', trips_path, data: { turbolinks: false} %>
<div id="map"></div>

<script>
  $('.location_form, .comment_form').hide();

  $('#add_new_location').click(function() {
    $('.location_form').toggle();
  });

  $('#add_new_comment').click(function() {
    $('.comment_form').toggle();
  });
</script>